### ISSUE TITLE
punycode module is deprecated

### ISSUE THREAD

**Issue by milahu** [PerimeterX/restringer#111] opened 2024-02-13 11:42 UTC
this warning shows at the end of every restringer run

```
(node:65863) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

i am installing dependencies with `pnpm install` so im ignoring the npm lockfile

**Comment by BenBaryoPX** [comment] 2024-02-15 08:53
@milahu Thanks for reaching out.
I can't reproduce on my machine. I've cloned and installed using pnpm, but didn't get the error.
If you can provide a minimal reproducible example I can continue to investigate the issue.

**Comment by BenBaryoPX** [comment] 2024-02-15 11:34
I see. On version 21 it does show this error. 
This is something to do with nested dependencies:
```
restringer@1.10.2
├─┬ eslint@8.56.0
│ └─┬ ajv@6.12.6
│   └─┬ uri-js@4.4.1
│     └── punycode@2.3.1 deduped
└─┬ jsdom@23.2.0
  ├─┬ tough-cookie@4.1.3
  │ └── punycode@2.3.1
  └─┬ whatwg-url@14.0.0
    └─┬ tr46@5.0.0
      └── punycode@2.3.1 deduped
```

Unfortunately, the only fix I can think of right now is living with the error until the dependencies are updated.
You can roll back to a previous Node.js version where this error doesn't show up, but since it's not a direct dependency on my side, I don't think there's anything for me to do here.

I'll be closing the issue, but I'll be happy for other recommendations if anyone has any - feel free to re-open the issue.

**Closed by BenBaryoPX** 2024-02-15 11:34 UTC

**Comment by milahu** [comment] 2024-02-15 12:10
aah, the joy of waiting for maintainers...

- https://github.com/garycourt/uri-js/pull/95 - uri-js is unmaintained
- https://github.com/ajv-validator/ajv/pull/2377
- https://github.com/eslint/eslint/issues/17720 - waiting for ajv

fixed

- https://github.com/salesforce/tough-cookie/pull/346
- https://github.com/jsdom/tr46/issues/53
